extraction:
  cpp:
    prepare:
      packages: 
        - cmake
        - g++
        - build-essential
        - git
        - libeigen3-dev
    configure:
      command:
        - mkdir .third-party && cd .third-party
        - git clone https://github.com/jlblancoc/nanoflann
        - cd nanoflann
        - mkdir build && cd build
        - cmake .. -DNANOFLANN_BUILD_EXAMPLES=OFF -DNANOFLANN_BUILD_TESTS=OFF
        - make && sudo make install
        - cd ../..
        - git clone https://github.com/MIT-SPARK/TEASER-plusplus
        - cd TEASER-plusplus
        - git checkout d79d0c67
        - mkdir build && cd build
        - cmake .. -DBUILD_TESTS=OFF -DBUILD_PYTHON_BINDINGS=OFF -DBUILD_DOC=OFF
        - make && sudo make install
        - cd ../..
        - cd ..
        - mkdir build && cd build
        - cmake .. -DKCP_BUILD_PYTHON_BINDING=OFF -DKCP_BUILD_DOC=OFF
    index:
      build_command:
        - cd build
        - make