name: Build
on:
  pull_request:
    branches:
      - main

jobs:
  build-kcp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: "3.10"

    - name: Install dependencies (1/3) (GCC, CMake, Eigen3, Doxygen, Graphviz)
      run: |
        sudo apt update
        sudo apt install -y g++ build-essential cmake libeigen3-dev doxygen graphviz

    - name: Install dependencies (2/3) (nanoflann)
      run: |
        git clone https://github.com/jlblancoc/nanoflann
        cd nanoflann
        mkdir build && cd build
        cmake .. -DNANOFLANN_BUILD_EXAMPLES=OFF -DNANOFLANN_BUILD_TESTS=OFF
        make
        sudo make install

    - name: Install dependencies (3/3) (TEASER++)
      run: |
        git clone https://github.com/MIT-SPARK/TEASER-plusplus
        cd TEASER-plusplus
        git checkout d79d0c67
        mkdir build && cd build
        cmake .. -DBUILD_TESTS=OFF -DBUILD_PYTHON_BINDINGS=OFF -DBUILD_DOC=OFF
        make
        sudo make install

    - name: Build the KCP library
      run: |
        mkdir build && cd build
        cmake .. -DKCP_BUILD_PYTHON_BINDING=ON -DPYTHON_EXECUTABLE=$(which python3) -DKCP_BUILD_DOC=ON
        make
